apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.jobname }}
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
      - name: {{ .Values.container.name }}
        image: {{ .Values.container.image }}
      restartPolicy: Never
